name: "Dispatch"

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  repository_dispatch:
    types: [run_tests]
  workflow_dispatch:


jobs:
  tests:
    name: 🎯 Dispatch changes
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: 🧰 Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: ✉️ Run Documentation generator
      if: ${{ env.DISPATCH_TOKEN != '' }}
      uses: mvasigh/dispatch-action@main
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        repo: Documentation
        owner: WerWolv
        event_type: update_pl_docs
